############################
# SITE SETTINGS
############################

# Website name
title: "iannakiEducation&Research"

# Website URL (update with your actual domain)
baseURL: "https://example.com/"

############################
# LANGUAGE SETTINGS
############################

# Default language
defaultContentLanguage: "en"
hasCJKLanguage: false
defaultContentLanguageInSubdir: true # Enable subdirectories for multilingual support

# Configure multiple languages
languages:
  en:
    languageName: "English"
    weight: 1 # Determines language order
    contentDir: "content/en"
  fr:
    languageName: "Français"
    weight: 2
    contentDir: "content/fr"

############################
# CONTENT & TAXONOMIES
############################

# Taxonomies for the site
taxonomies:
  author: "authors"
  tag: "tags"
  publication_type: "publication_types"

# Permalinks configuration (shortened paths for tags to avoid long filenames)
permalinks:
  authors: "/author/:slug/"
  tags: "/tags/:slug/"
  publication_types: "/publication/:slug/"

############################
# BUILD SETTINGS
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10

# File and alias configurations
ignoreFiles:
  - "\\.ipynb$"
  - "\\.ipynb_checkpoints$"
  - "\\.Rmd$"
  - "\\.Rmarkdown$"
  - "_cache$"

# Disable automatic alias generation to avoid unnecessary files
disableAliases: true

############################
# OUTPUT FORMATS
############################

outputs:
  home: 
    - HTML
    - RSS
    - headers
    - redirects
    - backlinks
  section: 
    - HTML
    - RSS

############################
# IMAGE PROCESSING
############################

imaging:
  resampleFilter: "lanczos"
  quality: 80
  anchor: "smart"

############################
# MARKUP SETTINGS
############################

markup:
  highlight:
    lineNos: false

############################
# ADVANCED SETTINGS
############################

# Enable emojis and robots.txt
enableEmoji: true
enableRobotsTXT: true

# Footnote return link format
footnotereturnlinkcontents: "<sup>^</sup>"

# Timeout for Hugo build process (in milliseconds)
timeout: 600000

############################
# SECURITY SETTINGS
############################

security:
  _merge: "deep"

############################
# SITEMAP CONFIGURATION
############################

sitemap:
  _merge: "deep"
