# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

############################
# SITE SETTINGS
############################

# Website name
title: "iannakiEducation&Research"

# Website URL (update with your actual domain)
baseURL: "https://example.com/"

############################
# LANGUAGE
############################

defaultContentLanguage: "en"
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
# CONTENT & TAXONOMIES
############################

# Taxonomies for the site
taxonomies:
  author: "authors"
  tag: "tags"
  publication_type: "publication_types"

# Permalinks configuration
permalinks:
  authors: "/author/:slug/"
  tags: "/tags/:slug/"
  publication_types: "/publication/:slug/"

############################
# BUILD SETTINGS
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10

# File and alias configurations
ignoreFiles:
  - "\\.ipynb$"
  - "\\.ipynb_checkpoints$"
  - "\\.Rmd$"
  - "\\.Rmarkdown$"
  - "_cache$"

disableAliases: true

############################
# OUTPUT FORMATS
############################

outputs:
  home: 
    - HTML
    - RSS
    - headers
    - redirects
    - backlinks
  section: 
    - HTML
    - RSS

############################
# IMAGE PROCESSING
############################

imaging:
  resampleFilter: "lanczos"
  quality: 80
  anchor: "smart"

############################
# MARKUP SETTINGS
############################

markup:
  highlight:
    lineNos: false

############################
# ADVANCED SETTINGS
############################

enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: "<sup>^</sup>"

# Timeout for Hugo build process (in milliseconds)
timeout: 600000

############################
# SECURITY SETTINGS
############################

security:
  _merge: "deep"

############################
# SITEMAP CONFIGURATION
############################

sitemap:
  _merge: "deep"
