# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# French language configuration
fr:
  languageCode: fr
  contentDir: content/fr
  title: iannakiEducation&Recherche
  params:
    description: Description du site en français...
  menu:
    main:
      - name: À propos
        url: '#about'
        weight: 1

# Uncomment the lines below to configure your website in a second language.
# zh:
#   languageCode: zh-Hans
#   contentDir: content/zh
#   title: Chinese website title...
#   params:
#     description: Site description in Chinese...
#   menu:
#     main:
#       - name: 传
#         url: '#about'
#         weight: 1
