# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language (English)
en:
  languageCode: en-us
  contentDir: content/en
  title: iannakiEducation&Research
  params:
    description: The official site of Ihababdelbasset Annaki, showcasing research, education, and academic projects.
  menu: main # Points to the English menu file

# French language configuration
fr:
  languageCode: fr
  contentDir: content/fr
  title: iannakiEducation&Recherche
  params:
    description: Le site officiel d'Ihababdelbasset Annaki, présentant des recherches, des projets éducatifs et académiques.
  menu: main_fr # Points to the French menu file

# Uncomment the lines below to configure your website in a second language.
# zh:
#   languageCode: zh-Hans
#   contentDir: content/zh
#   title: Chinese website title...
#   params:
#     description: Site description in Chinese...
#   menu:
#     main:
#       - name: 传
#         url: '#about'
#         weight: 1
