# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# French is the primary language
fr:
  languageCode: fr
  #contentDir: content/fr

en:
  languageCode: en-us
  #contentDir: content/en
