main:
  - name: Bio
    url: /en/
    weight: 10
  - name: Papers
    url: /#papers
    weight: 11
  - name: Talks
    url: /#talks
    weight: 12
  - name: News
    url: /#news
    weight: 13
  - name: Experience
    url: /experience/
    weight: 20
  - name: Projects
    url: /projects/
    weight: 30
  - name: Teaching
    url: /teaching/
    weight: 40

main_fr:
  - name: Bio
    url: /fr/
    weight: 10
  - name: Articles
    url: /fr/#papers
    weight: 11
  - name: Présentations
    url: /fr/#talks
    weight: 12
  - name: Actualités
    url: /fr/#news
    weight: 13
  - name: Expérience
    url: /fr/experience/
    weight: 20
  - name: Projets
    url: /fr/projects/
    weight: 30
  - name: Enseignement
    url: /fr/teaching/
    weight: 40
