name: Deploy to gh-pages branch

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'next/**'
      - '.github/workflows/deploy-gh-pages.yml'

concurrency:
  group: deploy-gh-pages-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      CI: true
      NEXT_TELEMETRY_DISABLED: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'next/package-lock.json'

      - name: Install dependencies
        working-directory: ./next
        run: npm ci || npm install --no-audit --no-fund

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: next/.next/cache
          key: nextjs-${{ runner.os }}-${{ hashFiles('next/package.json') }}-${{ github.sha }}
          restore-keys: |
            nextjs-${{ runner.os }}-${{ hashFiles('next/package.json') }}-
            nextjs-${{ runner.os }}-

      - name: Build static export
        working-directory: ./next
        env:
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
          NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
          NEXT_PUBLIC_SANITY_API_VERSION: ${{ secrets.NEXT_PUBLIC_SANITY_API_VERSION }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          NEXT_PUBLIC_SITE_NAME: ${{ secrets.NEXT_PUBLIC_SITE_NAME }}
          NEXT_PUBLIC_SITE_DESCRIPTION: ${{ secrets.NEXT_PUBLIC_SITE_DESCRIPTION }}
          NEXT_PUBLIC_FORMSPREE_ENDPOINT: ${{ secrets.NEXT_PUBLIC_FORMSPREE_ENDPOINT }}
          NEXT_PUBLIC_GA_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_GA_MEASUREMENT_ID }}
          GITHUB_SHA: ${{ github.sha }}
        run: npm run build

      - name: Add .nojekyll
        run: |
          touch next/out/.nojekyll

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: next/out
          publish_branch: gh-pages
          force_orphan: true
